# Generated by Django 5.0.6 on 2024-06-12 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_remove_aula_grupos_aula_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificacion',
            unique_together={('usuario', 'aula')},
        ),
    ]
