# Generated by Django 5.0.6 on 2024-06-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_alter_notificacion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificacion',
            unique_together=set(),
        ),
    ]
