version: '3.9'

services:
# Django Gunicorn
  web:
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Volumen para archivos estáticos
      - media_volume:/app/media         # Volumen para archivos cargados
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - influxdb
    command: >
              bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      gunicorn -c gunicorn-cfg.py core.wsgi:application"
# Celery Worker
  worker:
      build: .
      restart: always
      volumes:
          - .:/app
      env_file: .env
      depends_on:
          - web
          - redis
      command: celery -A core.celery worker --loglevel=info   
# Celery Beat
  beat:
      build: .
      restart: always
      volumes:
          - .:/app
      env_file: .env
      depends_on:
          - web
          - redis
      command: celery -A core.celery beat -l INFO 
# PostgreSQL Database
  db:
    image: postgres:16.3-bullseye
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
# Admin PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - db
# Redis
  redis:
    image: redis:7.2.5
    restart: always
# InfluxDB
  influxdb:
    image: influxdb:2.7.6
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
# Nginx
  nginx:
    image: "nginx:1.27.0" 
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d
      - static_volume:/app/staticfiles  # Volumen compartido para archivos estáticos
      - media_volume:/app/media         # Volumen compartido para archivos cargados
    depends_on: 
      - web

volumes:
  postgres_data:
  influxdb_data:
  static_volume:
  media_volume: