version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    #container_name: nginx
    restart: always
    image: "nginx:latest" #elegir versión aquí
    ports:
      - "85:85"  # revisar puertos
    volumes:
      - ./nginx:/etc/nginx/conf.d
    # - static:/sdasd/static 
    networks:
      - web_network #esto queeeeees?
    depends_on: 
      - appseed-app #web
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge